version: '3.8'

services:
  spring-boot-app:
    build: .
    container_name: spring-boot-app
    expose:
      - "8080"
    networks:
      - common_network

networks:
  common_network:
    external: true